---
title: "East Africa Poverty Indicators"
author: "Mburu"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float:
      collapsed: false
      smooth_scroll: false
    theme: united
    highlight: pygments
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

## Data 
[kenya poverty data](https://data.humdata.org/dataset/world-bank-poverty-indicators-for-kenya)
[Uganda poverty data](https://data.humdata.org/dataset/world-bank-poverty-indicators-for-uganda)
[Tanzania poverty data](https://data.humdata.org/dataset/world-bank-poverty-indicators-for-tanzania)
[Tanzania poverty data](https://data.humdata.org/dataset/world-bank-poverty-indicators-for-rwanda)

### Packages used

```{r}
library(plotly)
library(tidyverse)
library(data.table)
library(sf)
library(DT)
library(tmap)
library(ggthemes)
```

## Read data

- Read data and row bind

```{r}
poverty_ken <- fread("poverty_data/poverty_ken.csv")

poverty_uga <- fread("poverty_data/poverty_uga.csv")

poverty_tza <- fread("poverty_data/poverty_tza.csv")

poverty_rwa <- fread("poverty_data/poverty_rwa.csv")

poverty_ea <- rbind(poverty_ken, poverty_uga, poverty_rwa, poverty_tza)

poverty_ea[sample(nrow(poverty_ea), 10)] %>% datatable(options = list(scrollX = TRUE))
```

## Minor Cleaning

- Convert column names into lower 
- Replace space with underscore


```{r}
nms_old <- names(poverty_ea) 
nms_old

nms_new <- nms_old %>% tolower() 
nms_new <- gsub("\\s", "_", nms_new)
nms_new

setnames(poverty_ea, nms_old, nms_new)
poverty_ea[, value:= as.numeric(value)]
poverty_ea <-  poverty_ea[!is.na(value)]

poverty_ea[sample(nrow(poverty_ea), 10)] %>% datatable(options = list(scrollX = TRUE))

```

## Plots



```{r}
poverty_ea[, year := as.numeric(year)]

poverty_ea <- poverty_ea[!grepl("^Annu", indicator_name)]
poverty_ea_split <- split(poverty_ea, f = poverty_ea$indicator_name)
i = 1
n <- length(poverty_ea_split)
my_plots <-htmltools::tagList()
for (i in 1:n) {
    df = poverty_ea_split[[i]]
    my_title = df[, unique(indicator_name)]
    mn = df[, min(year)]
    mx = df[, max(year)]
    breaks = seq(mn, mx,by = 2)
    p = ggplot(df, aes(year, value, group = country_name, color = country_name) ) +
        geom_line()+
        theme_fivethirtyeight()+
        labs(title = my_title, x = "year", y = "%")+
      scale_color_viridis_d(name="")+
      scale_x_continuous(breaks = breaks)
    
    my_plots[[i]] = ggplotly(p)
    
}

my_plots
```




```{r}
economy_and_growth <- fread("API_3_DS2_en_csv_v2_1743760.csv") 

nms_old <- economy_and_growth[1,]  %>% as.character()
nms_old
economy_and_growth <- economy_and_growth[-1,]
names(economy_and_growth) <- nms_old
nms_new <- nms_old %>% tolower() 
nms_new <- gsub("\\s", "_", nms_new)
nms_new

setnames(economy_and_growth, nms_old, nms_new)

id_vars <- c("country_name", "country_code",
             "indicator_name", "indicator_code")

economy_and_growth <- melt(economy_and_growth,
                                id.vars = id_vars, 
                           variable.factor = F,
                           value.factor = F,
                           variable.name = "year")
economy_and_growth[, value:= as.numeric(value)]

economy_and_growth[, year := as.numeric(year)]
economy_and_growth <-  economy_and_growth[!is.na(value)|!is.na(year)]
economy_and_growth[sample(nrow(economy_and_growth), 10)] %>% datatable(options = list(scrollX = TRUE))
```



```{r}
gni_gdp_savings_vec <- c("Gross savings (% of GNI)", 
                         "Total debt service (% of exports of goods, services and primary income)",
                         "Total debt service (% of GNI)",
                         "General government final consumption expenditure (annual % growth)",
                         "Trade (% of GDP)",
                         "Price level ratio of PPP conversion factor (GDP) to market exchange rate")
ea_country <- c("Kenya", "Uganda", "Rwanda", "Tanzania")
gni_gdp_savings_df <- economy_and_growth[indicator_name %in% gni_gdp_savings_vec & country_name %in% ea_country ]
```



```{r}
ggplot(gni_gdp_savings_df,
       aes(year, value, group = country_name, 
           color = country_name))+
  facet_wrap(~indicator_name, scales = "free")+
  geom_line()
```