name: "m_mburu"
navbar:
  title: "ML/Viz/Spatial/Philosophy/Stats"
  left:
    - text: "Home"
      href: index.html
  right: 
    - icon: fa-github fa-lg
      href: http://github.com/m-mburu/

theme: jekyll-theme-darkly