ame: "Data Analysis Blog"
navbar:
  title: "M Mburu"
  left:
    - text: "Home"
      href: index.html
  right: 
    - icon: fa-github fa-lg
      href: http://github.com/m-mburu/

theme: jekyll-theme-slate