project:
  type: website
  output-dir: docs

website:
  title: "Data Science Projects"
  navbar:
    search: true
    background: dark 
    type: dark
    display: inline-block;
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: blogs.qmd
        text: Blog

format:
  html:
    theme: lumen
    toc: true

editor: visual

