project:
  type: website
  output-dir: docs

website:
  title: "Mburu Blog"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Data Camp Courses 
        href: datacamp.qmd
      
    right:
      - about.qmd
      - icon: github
        href: https://github.com/m-mburu
      - icon: twitter
        href: https://twitter.com/mmburu_w
format:
  html:
    theme: lumen
    css: style.css

editor: visual

