project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "posts/**/*.qmd"
    - "posts/**/*.Rmd"
  resources:
    - style.css

website:
  title: "Mburu M"
  site-url: https://m-mburu.github.io/
  favicon: "milkyway.jpeg"
  google-analytics: "G-BFNZ97VTLJ"
  open-graph: true
  twitter-card: true
  page-navigation: true
  reader-mode: true  
  navbar:
    title: "Mburu M"
    search: true
    collapse-below: lg
    left:
      - text: Home
        href: index.qmd
    
    right:
      - text: About
        href: about.qmd
      - icon: github
        href: https://github.com/m-mburu
      - icon: twitter
        href: https://twitter.com/mmburu_w
format:
    html:
        html-math-method: mathjax
        theme: 
          dark: darkly
          light: flatly
        toc: true
        toc-depth: 4 
        smooth-scroll: true
        include-in-header: _includes/cache-bust-css.html
        warning: false
        error: false
        lang: en

editor: visual
