project:
  type: website
  output-dir: docs

website:
  title: "Mburu Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/m-mburu
      - icon: twitter
        href: https://twitter.com/mmburu_w
format:
  html:
    theme: cosmo
    css: style.css

editor: visual

