project:
  type: website
  output-dir: docs

website:
  title: "Data Science Projects"
  navbar:
    search: true
    background: light
    type: light
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: blogs.qmd
        text: Blog

format:
  html:
    theme: lumen
    css: style.css
    toc: true

editor: visual

