project:
  type: website
  output-dir: docs

website:
  title: "Personal Blog"
  site-url: https://m-mburu.github.io/
  favicon: "milkyway.jpeg"
  google-analytics: "G-BFNZ97VTLJ"
  open-graph: true
  twitter-card: true
  page-navigation: true
  reader-mode: true  
  navbar:
    search: true
    background: dark
    collapse-below: lg
    type: overlay 
    alignment: center
    left:
      - text: Home
        href: index.qmd
      - text: Data Camp Courses 
        href: datacamp.qmd
      - text: Shiny Apps
        href: shiny_apps.qmd 
    
    right:
      - about.qmd
      - icon: github
        href: https://github.com/m-mburu
      - icon: twitter
        href: https://twitter.com/mmburu_w
format:
    html:
        toc: true
        toc-depth: 4 
        smooth-scroll: true
        css: style.css
        warning: false
        error: false
        lang: en


editor: visual
