project:
  type: website
  output-dir: docs

website:
  title: "Data Science & Stats Lab"
  site-url: https://m-mburu.github.io/
  favicon: "milkyway.jpeg"
  google-analytics: "G-BFNZ97VTLJ"
  open-graph: true
  twitter-card: true
  page-navigation: true
  reader-mode: true  
  navbar:
    title: "Data Science"
    search: true
    background: primary
    collapse-below: lg
    left:
      - text: Home
        href: index.qmd
    
    right:
      - text: About
        href: about.qmd
      - icon: github
        href: https://github.com/m-mburu
      - icon: twitter
        href: https://twitter.com/mmburu_w
format:
    html:
        theme: 
          light: flatly
          dark: darkly
        toc: true
        toc-depth: 4 
        smooth-scroll: true
        css: style.css
        warning: false
        error: false
        lang: en


editor: visual
