---
title: "My ML/Viz/Spatial Journey/ Just having Fun"
author: "Mburu"
date: "4/18/2020"
output:
  github_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



| Description | Notebook | Source Code
| ------------- | ------------- | ------------- |
| Breast cancer prediction | [Notebook (HTML)](https://m-mburu.github.io/breast_cancer_prediction/cancer_data.html) | [R Markdown (Rmd)](breast_cancer_prediction/cancer_data.Rmd)  |
| Busara task | [Notebook (HTML)](https://m-mburu.github.io/busara_task/busara-data-analysis.html) | [R Markdown (Rmd)](busara_task/busara data analysis.Rmd)  |
| Zindi loan prediction | [Notebook (HTML)](https://m-mburu.github.io/loan_prediction/loan_prediction.html) | [R Markdown (Rmd)](loan_prediction/loan_prediction.Rmd)  |
| TZ Water Pumps | [Notebook (HTML)](https://m-mburu.github.io/water_pumps_tz/water_pumps.html) | [R Markdown (Rmd)](water_pumps_tz/water_pumps.Rmd)  |
| Intro to dimension reduction | [Notebook (HTML)](https://m-mburu.github.io/introduction-to-advanced-dimensionality-reduction/introduction_dimensionality_reduction.html) | [R Markdown (Rmd)](ntroduction-to-advanced-dimensionality-reduction/introduction_dimensionality_reduction.Rmd)  |
| Clustering | [Notebook (HTML)](https://m-mburu.github.io/introduction-to-advanced-dimensionality-reduction/clustering_fashion_mnist.html) | [R Markdown (Rmd)](ntroduction-to-advanced-dimensionality-reduction/clustering_fashion_mnist.Rmd)  |
| Kenya maps | [Notebook (HTML)](https://m-mburu.github.io/kenya_population/kenya_maps.html) | [R Markdown (Rmd)](/kenya_population/kenya_maps.Rmd)  |
| Kenya 2019 household assets | [Notebook (HTML)](https://m-mburu.github.io/kenya_population/household_assets_2019census.html) | [R Markdown (Rmd)](/kenya_population/household_assets_2019census.Rmd)  | 
| Introduction to association analysis |[Notebook (HTML)](https://m-mburu.github.io/association_analysis/association_analysis.html) | [R Markdown (Rmd)](/association_analysis/association_analysis.Rmd)  |
| Digit recognition MNIST |[Notebook (HTML)](https://m-mburu.github.io/kaggle/mnist_digits/mnist.html) | [R Markdown (Rmd)](/kaggle/mnist_digits/mnist.Rmd)|
| ML with tree models|[Notebook (HTML)](https://m-mburu.github.io/datacamp/ml_tree_methods_r/ml_tree_methods.html) | [R Markdown (Rmd)](/datacamp/ml_tree_methods_r/ml_tree_methods.Rmd))|
| Network Analysis |[Notebook (HTML)](https://m-mburu.github.io/datacamp/network-analysis-in-r/network_analysis_r.html) | [R Markdown (Rmd)](/datacamp/network-analysis-in-r/network_analysis_r.Rmd))|
| Airbnb NYC |[Notebook (HTML)](https://m-mburu.github.io/kaggle/newyork_airbnb/newyork_airbnb.html) | [R Markdown (Rmd)](/kaggle/newyork_airbnb/newyork_airbnb.Rmd)|
| Explainable ML |[Notebook (HTML)](https://m-mburu.github.io/kaggle/heart_disease/heart_disease.html) | [R Markdown (Rmd)](/kaggle/heart_disease/heart_disease.Rmd)|
| Introduction to deep learning |[Notebook (HTML)](https://m-mburu.github.io/datacamp/introduction_deeplearning/introduction-to-deep-learning-in-python.html) | [Python notebook (ipnb)](/datacamp/introduction_deeplearning/introduction-to-deep-learning-in-python.ipynb)|
| Mburu CV |[Notebook (HTML)](https://m-mburu.github.io/cv/cv_mburu.html) | [Rmarkdown (ipnb)](/cv/cv_mburu.Rmd)|


