---
title: "World Health 2020 STATS"
author: "Mburu"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float:
      collapsed: false
      smooth_scroll: false
    theme: united
    highlight: pygments
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```


```{r}
library(tidyverse)
library(data.table)
library(DT)
library(ggthemes)
library(leaflet)
library(ggmap)
library(plotly)
library(lubridate)
adolescentBirthRate <- fread("data/adolescentBirthRate.csv")
```



```{r}
old_nms <- names(adolescentBirthRate)
old_nms
old_nms <- old_nms %>% tolower()
old_nms <- gsub("\\s", "_", old_nms)
old_nms
names(adolescentBirthRate) <- old_nms

head(adolescentBirthRate, 10) %>% datatable()
```



```{r}

ea_country <- c("Kenya", "Uganda",  "Tanzania")

ea_data <- adolescentBirthRate[location %in% ea_country ]

p = ggplot(ea_data, aes(period, first_tooltip, group = location, color = location) ) +
    geom_line(sizee = 1)+
    theme_hc()+
    labs(title = "", x = "Year", y = "%")+
    scale_color_viridis_d(name="")
p
```

