{
  "hash": "d1680ee8ffe2b85ad2ec29235f73512f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Your Supervisor Said 'Do a Bootstrap'. What Do They Mean?\"\nformat: html\ndate: \"2026-02-23\"\ndescription: \"A practical journey from one sample to bootstrap confidence intervals and hypothesis tests using children's weight-for-height z-scores.\"\nshare-permalink: \"https://m-mburu.github.io/posts/bootstrap/boostrap_crab.html\"\ncategories: [\"Data & Evidence\", \"Statistics\", \"Bootstrap\"]\n---\n\n\n\nLet us say you are a PhD candidate. You have spent months cleaning your data,\nfitting your model, and preparing the results. You show the results to your\nsupervisors. One of them looks at your confidence interval and asks:\n\n> Did you bootstrap this?\n\nAnother one adds:\n\n> Carry out a bootstrap and see whether the conclusion remains the same.\n\nYou write the comment down. But perhaps you are not completely sure what they\nhave asked you to do. Is bootstrap another statistical test? Is it a way of\ncorrecting a bad model? And why does a serious statistical method have the name\nof something attached to a boot?\n\nThe same can happen in a management meeting. A statistician says that the\nconfidence intervals were bootstrapped. If you are not a statistician, you may\nwonder what this means and whether it changes the decision.\n\nIn this article I will use a simple example of children's weight-for-height\nz-scores to explain bootstrap. We will first do an ordinary test, then carry\nout the same test using bootstrap.\n\n## Why does it have such a strange name?\n\nBaron Münchhausen was a fictional nobleman famous for telling impossible\nstories. In one of the stories, he and his horse became trapped in a swamp. He\nclaimed that he escaped by pulling himself and the horse out using his own\nhair.\n\nThe expression “pull yourself up by your own bootstraps” came later. It means\ndoing something that appears impossible without help from outside. In the\noriginal story the Baron used his hair, not his bootstraps.\n\nStatistics has a similar problem. We want to know what would happen if we\nrepeated our study many times and collected a new sample each time. Usually, we\ndo not have the money or time to repeat the whole study. We have only one\nsample.\n\nIn bootstrap we use the one sample we have to create many new samples. Bradley\nEfron formally introduced the statistical method in his 1979 paper,\n[“Bootstrap Methods: Another Look at the\nJackknife”](https://doi.org/10.1214/aos/1176344552). The stories of Baron\nMünchhausen can also be read through [Project\nGutenberg](https://www.gutenberg.org/ebooks/3154).\n\nIn simple terms:\n\n> A bootstrap repeatedly resamples the data we observed, recalculates the\n> result, and uses the variation in those recalculated results to show how\n> uncertain our original result is.\n\nLet us see what this means using data.\n\n## A simple test using weight-for-height z-scores\n\nSuppose we collected weight and height measurements from children in a\ncommunity nutrition survey. We then converted each child's measurement into a\nweight-for-height z-score, which we will call WHZ.\n\nThe [WHO child growth\nstandards](https://www.who.int/tools/child-growth-standards/standards/weight-for-length-height)\ngive us a reference for interpreting the values:\n\n- A WHZ of 0 places a child at the WHO reference median for a child of the same\n  height.\n- A negative WHZ means the child is lighter for their height than the reference\n  median.\n- A positive WHZ means the child is heavier for their height than the reference\n  median.\n- An individual child with WHZ below -2 is classified as wasted.\n\nThe data below are simulated. This allows us to learn the method without\nsharing information about real children.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_children <- 80\n\nwhz <- rnorm(\n  n = n_children,\n  mean = -0.65,\n  sd = 1.05\n)\n\nwhz <- pmax(pmin(whz, 2.4), -3.8)\n\nchildren <- data.table(\n  child_id = seq_len(n_children),\n  whz = whz\n)\n\nchildren[\n  ,\n  wasted := whz < wasting_cutoff\n]\n\nchildren[1:10] |>\n  kable(\n    digits = 2,\n    col.names = c(\"Child\", \"WHZ\", \"WHZ below -2\")\n  )\n```\n\n::: {.cell-output-display}\n\n\n| Child|   WHZ|WHZ below -2 |\n|-----:|-----:|:------------|\n|     1| -0.10|FALSE        |\n|     2| -1.78|FALSE        |\n|     3| -0.50|FALSE        |\n|     4| -0.74|FALSE        |\n|     5| -1.35|FALSE        |\n|     6| -3.29|TRUE         |\n|     7| -1.42|FALSE        |\n|     8| -1.72|FALSE        |\n|     9| -0.53|FALSE        |\n|    10| -1.15|FALSE        |\n\n\n:::\n:::\n\n\nBefore running a test, let us look at the values.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Simulated weight-for-height z-scores. The dashed line at 0 is the WHO reference median; the red line at -2 is the wasting cut-off.](boostrap_crab_files/figure-html/plot-whz-1.png){width=768}\n:::\n:::\n\n\nThe sample mean is -0.74. It is below zero, so the\nchildren in this sample are lighter for their height than the WHO reference\nmedian on average.\n\nBut a sample mean is not a population mean. A different sample of 80 children\nwould give us a different answer. Our first question is:\n\n> Is the population mean WHZ below 0, or could the negative sample mean simply\n> be sampling variation?\n\nThis can be written as:\n\n$$\nH_0: \\mu = 0\n\\qquad \\text{against} \\qquad\nH_1: \\mu < 0.\n$$\n\nThe null hypothesis says that the population mean WHZ is at the reference\nmedian. The alternative says it is below the reference median.\n\nThis is not yet a test of how many children are wasted. A mean below 0 and an\nindividual WHZ below -2 are different things. We will return to that\ndistinction.\n\n## The ordinary one-sample test\n\nThe familiar approach is a one-sample t-test.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclassical_test <- t.test(\n  children$whz,\n  mu = null_mean,\n  alternative = \"less\"\n)\n\nclassical_results <- data.table(\n  `Sample mean` = mean(children$whz),\n  `t statistic` = unname(classical_test$statistic),\n  `p-value` = classical_test$p.value\n)\n\nkable(classical_results, digits = 4)\n```\n\n::: {.cell-output-display}\n\n\n| Sample mean| t statistic| p-value|\n|-----------:|-----------:|-------:|\n|     -0.7397|     -6.6449|       0|\n\n\n:::\n:::\n\n\nThe p-value is 1.77\\times 10^{-9}. If the population mean\nwere really 0, a sample result this far below 0 would be\nunusual\nunder the assumptions of the t-test.\n\nThe t-test compares our observed mean with what we would expect if the\npopulation mean were zero. It does this using a t-distribution. We now want to\nsee whether bootstrap gives us the same conclusion.\n\nWe start with one bootstrap sample before repeating the process 5,000 times.\n\n## Taking one bootstrap sample\n\nFor a small demonstration, take the first 10 WHZ values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsmall_sample <- children$whz[1:10]\n\nset.seed(27)\none_resample <- sample(\n  small_sample,\n  size = length(small_sample),\n  replace = TRUE\n)\n\nresample_example <- data.table(\n  position = seq_along(small_sample),\n  observed_whz = small_sample,\n  resampled_whz = one_resample\n)\n\nkable(\n  resample_example,\n  digits = 2,\n  col.names = c(\"Position\", \"Observed WHZ\", \"One bootstrap resample\")\n)\n```\n\n::: {.cell-output-display}\n\n\n| Position| Observed WHZ| One bootstrap resample|\n|--------:|------------:|----------------------:|\n|        1|        -0.10|                  -1.35|\n|        2|        -1.78|                  -1.78|\n|        3|        -0.50|                  -3.29|\n|        4|        -0.74|                  -0.53|\n|        5|        -1.35|                  -1.72|\n|        6|        -3.29|                  -0.50|\n|        7|        -1.42|                  -0.10|\n|        8|        -1.72|                  -0.53|\n|        9|        -0.53|                  -0.10|\n|       10|        -1.15|                  -0.53|\n\n\n:::\n:::\n\n\nWe sampled 10 values from the original 10 values **with replacement**. After\ndrawing a value, we put it back before drawing again. This is why one value can\nappear several times while another value may not appear at all.\n\nThe original mean of these 10 values is -1.26. The\nmean of this particular resample is -1.04.\n\nOne resample does not tell us much. The next step is to repeat the process many\ntimes.\n\n## Repeating the sample 5,000 times\n\nWe now resample all 80 children 5,000 times. Each time, we\ncalculate the mean WHZ.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(310)\n\nbootstrap_means <- numeric(n_boot)\n\nfor (b in seq_len(n_boot)) {\n  whz_star <- sample(\n    children$whz,\n    size = n_children,\n    replace = TRUE\n  )\n\n  bootstrap_means[b] <- mean(whz_star)\n}\n\nmean_bootstrap_se <- sd(bootstrap_means)\nmean_bootstrap_ci <- percentile_interval(bootstrap_means)\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Bootstrap distribution of 5,000 sample means. The solid line is the observed sample mean.](boostrap_crab_files/figure-html/plot-bootstrap-means-1.png){width=768}\n:::\n:::\n\n\nThis graph is called the **bootstrap distribution of the mean**. It shows how\nthe mean changes when the observed sample is resampled again and again.\n\nThe standard deviation of these 5,000 means is\n0.109. We call this the bootstrap standard error. It\nis an estimate of the typical sampling variation in the mean.\n\nThe middle 95% of the bootstrap means run from\n-0.95 to -0.53. The\ninterval is entirely below zero. In practical language, the data suggest that\nthe population represented by this sample has a mean WHZ below the WHO\nreference median.\n\nNotice what we have done so far. We resampled the observations **without\nchanging them first**. This is useful for estimating the uncertainty around\nthe observed mean. It is not yet a valid bootstrap hypothesis test.\n\n## Preparing the data for a hypothesis test\n\nOur observed data have a negative mean. When we resample them as they are, the\nbootstrap samples will also tend to have a negative mean. That is exactly what\nwe want when building a confidence interval around the observed result.\n\nFor hypothesis testing we need to ask a different question:\n\n> What kind of test statistics would we observe if the null hypothesis were\n> true?\n\nThe null hypothesis says that the population mean is 0. We therefore create a\nworld where this is true by shifting every observed value by the same amount:\n\n$$\nx_i^{0} = x_i - \\bar{x} + \\mu_0,\n$$\n\nwhere $\\bar{x}$ is the observed mean and $\\mu_0$ is the value specified by the\nnull hypothesis. Here, $\\mu_0 = 0$.\n\nThis transformation keeps the shape and spread of the observed values, but\nmoves their mean to zero.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwhz_under_null <- children$whz -\n  mean(children$whz) +\n  null_mean\n\nnull_world_summary <- data.table(\n  Dataset = c(\"Observed data\", \"Recentered null data\"),\n  Mean = c(mean(children$whz), mean(whz_under_null)),\n  `Standard deviation` = c(sd(children$whz), sd(whz_under_null))\n)\n\nkable(null_world_summary, digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|Dataset              |  Mean| Standard deviation|\n|:--------------------|-----:|------------------:|\n|Observed data        | -0.74|              0.996|\n|Recentered null data |  0.00|              0.996|\n\n\n:::\n:::\n\n\nThe centre has moved to zero, but the standard deviation has not changed. We\ncan now resample from these recentered values to see what results the null\nworld produces.\n\n## Carrying out the bootstrap hypothesis test\n\nWe will use the same statistic as the ordinary t-test:\n\n$$\nT_{\\text{obs}}\n=\n\\frac{\\bar{x} - \\mu_0}{s/\\sqrt{n}}.\n$$\n\nFor every null bootstrap sample, we calculate:\n\n$$\nT^{*(b)}\n=\n\\frac{\\bar{x}^{*(b)} - \\mu_0}{s^{*(b)}/\\sqrt{n}}.\n$$\n\nThis is called a *studentized* statistic because the difference in means is\nscaled by its estimated standard error. A large negative value provides\nevidence for our alternative hypothesis that $\\mu < 0$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nobserved_t <- one_sample_t(\n  children$whz,\n  mu = null_mean\n)\n\nset.seed(711)\nnull_bootstrap_t <- numeric(n_boot)\n\nfor (b in seq_len(n_boot)) {\n  whz_star <- sample(\n    whz_under_null,\n    size = n_children,\n    replace = TRUE\n  )\n\n  null_bootstrap_t[b] <- one_sample_t(\n    whz_star,\n    mu = null_mean\n  )\n}\n\nbootstrap_p_value <- monte_carlo_p(\n  simulated_statistics = null_bootstrap_t,\n  observed_statistic = observed_t,\n  tail = \"left\"\n)\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Bootstrap null distribution of the t-statistic. The red line is the statistic observed in the original sample.](boostrap_crab_files/figure-html/plot-null-bootstrap-1.png){width=768}\n:::\n:::\n\n\nThe observed t-statistic is -6.64. The bootstrap p-value is\n2\\times 10^{-4}.\n\nThe p-value is the proportion of bootstrap samples generated under the null\nhypothesis that produced a t-statistic at least as negative as the one we\nobserved. We use the small Monte Carlo correction:\n\n$$\n\\widehat{p}\n=\n\\frac{\n  1 + \\#\\left\\{T^{*(b)} \\leq T_{\\text{obs}}\\right\\}\n}{\n  B + 1\n}.\n$$\n\nThe 1 in the numerator and denominator prevents us from reporting a p-value of\nexactly zero merely because a finite simulation did not produce a more extreme\nresult.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntest_comparison <- data.table(\n  Method = c(\n    \"Classical one-sample t-test\",\n    \"Nonparametric bootstrap test\"\n  ),\n  `p-value` = c(\n    classical_test$p.value,\n    bootstrap_p_value\n  )\n)\n\nkable(test_comparison, digits = 4)\n```\n\n::: {.cell-output-display}\n\n\n|Method                       | p-value|\n|:----------------------------|-------:|\n|Classical one-sample t-test  |   0e+00|\n|Nonparametric bootstrap test |   2e-04|\n\n\n:::\n:::\n\n\nThe two p-values do not have to be identical. The classical test uses the\nt-distribution as its null reference. The bootstrap test estimates the null\ndistribution by resampling the recentered data.\n\nWhat matters here is the substantive conclusion. Both methods indicate that\nthe negative sample mean would be difficult to explain if the population mean\nWHZ were really zero.\n\n## Mean WHZ is not the prevalence of wasting\n\nNo. This is an important distinction.\n\nOur mean analysis asked whether children are **below the WHO reference median\non average**. Wasting is an individual classification. According to the [WHO\ndefinition](https://www.who.int/data/gho/indicator-metadata-registry/imr-details/prevalence-of-malnutrition-%28weight-for-height-2-or--2-standard-deviation-from-the-median-of-the-who-child-growth-standards%29-among-children-under-5-years-of-age-by-type-%28wasting-and-overweight%29-%28sdg-2.2.2%29),\na child is wasted when WHZ is below -2.\n\nIf a manager asks, “What percentage of children are wasted?”, the statistic we\nneed is:\n\n$$\n\\widehat{\\pi}\n=\n\\frac{\n  \\text{number of children with WHZ below } -2\n}{\n  \\text{number of children measured}\n}.\n$$\n\nWe can bootstrap this proportion in the same way we bootstrapped the mean:\nresample children, calculate the proportion wasted, and repeat.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nobserved_wasting_prevalence <- mean(\n  children$whz < wasting_cutoff\n)\n\nset.seed(912)\nbootstrap_wasting_prevalence <- numeric(n_boot)\n\nfor (b in seq_len(n_boot)) {\n  whz_star <- sample(\n    children$whz,\n    size = n_children,\n    replace = TRUE\n  )\n\n  bootstrap_wasting_prevalence[b] <- mean(\n    whz_star < wasting_cutoff\n  )\n}\n\nwasting_prevalence_ci <- percentile_interval(\n  bootstrap_wasting_prevalence\n)\n```\n:::\n\n\nThe estimated prevalence of wasting is\n6.2%. The bootstrap interval runs\nfrom 1.2% to\n12.5%.\n\nFor a manager, the interval is often more useful than the point estimate\nalone. Another sample from the same population would not necessarily produce\nexactly 6.2%. The interval shows a\nplausible range of sampling uncertainty.\n\nThere is an additional warning. If the children came from a complex survey\nwith villages as clusters, strata, or unequal sampling weights, resampling\nindividual children as though they were independently selected may be wrong.\nThe bootstrap must respect the way the sample was collected.\n\n## The mathematics behind bootstrap\n\nLet us now write the same idea using statistical notation. Suppose the\npopulation follows an unknown distribution $F$. The quantity we want to\nestimate is:\n\n$$\n\\theta = t(F).\n$$\n\nThe function $t(F)$ can represent a population mean, median, prevalence, or\nregression coefficient. We observe a sample:\n\n$$\nX_1, X_2, \\ldots, X_n \\sim F,\n$$\n\nbut we do not know $F$. Bootstrap replaces $F$ with the empirical distribution\nof the values in our sample:\n\n$$\n\\widehat{F}_n(x)\n=\n\\frac{1}{n}\n\\sum_{i=1}^{n}\n\\mathbf{1}(X_i \\leq x).\n$$\n\nThis gives each observed value a probability of $1/n$. Sampling from\n$\\widehat{F}_n$ is therefore the same as sampling the observed values with\nreplacement.\n\nFor bootstrap sample $b$, we draw:\n\n$$\nX_1^{*(b)}, \\ldots, X_n^{*(b)}\n\\overset{\\text{i.i.d.}}{\\sim}\n\\widehat{F}_n,\n$$\n\nand calculate the statistic again:\n\n$$\n\\widehat{\\theta}^{*(b)}\n=\nt\\left(\\widehat{F}_n^{*(b)}\\right).\n$$\n\nThe collection of values $\\widehat{\\theta}^{*(1)}, \\ldots,\n\\widehat{\\theta}^{*(B)}$ is the bootstrap distribution. Its spread tells us\nhow much the statistic changes from one bootstrap sample to another.\n\nFor a percentile confidence interval we take the lower and upper percentiles:\n\n$$\n\\left[\n  \\widehat{\\theta}^{*}_{\\alpha/2},\n  \\widehat{\\theta}^{*}_{1-\\alpha/2}\n\\right].\n$$\n\nFor a 95% interval, these are the 2.5th and 97.5th percentiles. This is the\nmethod we used for the mean WHZ and wasting prevalence. Other methods, such as\nthe bootstrap-t and bias-corrected and accelerated intervals, may be more\nappropriate when the bootstrap distribution is highly skewed or biased.\n\n## Nonparametric and parametric bootstrap\n\nSo far, we have used the nonparametric bootstrap. It resamples the observed\nvalues. There is another common approach.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbootstrap_methods <- data.table(\n  Method = c(\"Nonparametric bootstrap\", \"Parametric bootstrap\"),\n  `What creates a new dataset?` = c(\n    \"Resampling the observed data\",\n    \"Simulation from a fitted probability model\"\n  ),\n  `Main assumption` = c(\n    \"The sample represents the population and the resampling scheme matches the design\",\n    \"The fitted model reasonably describes how the data arise\"\n  ),\n  `Question to ask` = c(\n    \"What exactly was resampled?\",\n    \"What model generated the simulated data?\"\n  )\n)\n\nkable(bootstrap_methods)\n```\n\n::: {.cell-output-display}\n\n\n|Method                  |What creates a new dataset?                |Main assumption                                                                   |Question to ask                          |\n|:-----------------------|:------------------------------------------|:---------------------------------------------------------------------------------|:----------------------------------------|\n|Nonparametric bootstrap |Resampling the observed data               |The sample represents the population and the resampling scheme matches the design |What exactly was resampled?              |\n|Parametric bootstrap    |Simulation from a fitted probability model |The fitted model reasonably describes how the data arise                          |What model generated the simulated data? |\n\n\n:::\n:::\n\n\nFor our WHZ data, a parametric bootstrap could assume a Normal distribution,\nestimate its mean and standard deviation, and simulate new values from that\nfitted distribution. For hypothesis testing, we would simulate under the null:\n\n$$\nX_i^*\n\\sim\n\\mathcal{N}\\left(\\mu_0, \\widehat{\\sigma}^2\\right).\n$$\n\nThis is convenient, but it adds a stronger assumption: that the Normal model is\na good description of the WHZ values.\n\n## Testing a model coefficient using the crab data\n\nSo far we have tested a sample mean. We can use the same bootstrap idea when\nthe hypothesis concerns a regression coefficient.\n\nLet us use the `crabs` dataset in the `MASS` package. It contains measurements\nfrom 200 crabs of two species. We will use `sp`, the crab species; `CW`, the\ncarapace width; and `sex`, whether the crab is female or male.\n\nSuppose our question is:\n\n> After accounting for carapace width, does sex help us distinguish the two\n> crab species?\n\nWe fit a logistic regression because the outcome has two categories. The full\nmodel is:\n\n$$\n\\log\\left(\n  \\frac{P(\\text{orange species})}\n       {1 - P(\\text{orange species})}\n\\right)\n=\n\\beta_0 + \\beta_1\\operatorname{CW} + \\beta_2\\operatorname{sex}.\n$$\n\nThe coefficient we are interested in is $\\beta_2$:\n\n$$\nH_0: \\beta_2 = 0\n\\qquad \\text{against} \\qquad\nH_1: \\beta_2 \\neq 0.\n$$\n\nIn ordinary language, the null hypothesis says that once width is in the\nmodel, adding sex does not improve the model.\n\n### Comparing the two crab models\n\nWe first fit two models. The reduced model represents the null hypothesis and\ncontains width only. The full model contains width and sex.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(crabs, package = \"MASS\")\n\ncrab_data <- as.data.table(crabs)\ncrab_data[, orange_species := as.integer(sp == \"O\")]\n\ncrab_reduced <- glm(\n  orange_species ~ CW,\n  family = binomial(link = \"logit\"),\n  data = crab_data\n)\n\ncrab_full <- glm(\n  orange_species ~ CW + sex,\n  family = binomial(link = \"logit\"),\n  data = crab_data\n)\n\ncrab_lrt <- anova(\n  crab_reduced,\n  crab_full,\n  test = \"Chisq\"\n)\n\nobserved_crab_lrt <- crab_lrt$Deviance[2]\nclassical_crab_p <- crab_lrt$`Pr(>Chi)`[2]\n\ncrab_model_result <- data.table(\n  Result = c(\n    \"Observed likelihood-ratio statistic\",\n    \"Classical p-value\"\n  ),\n  Value = c(observed_crab_lrt, classical_crab_p)\n)\n\nkable(crab_model_result, digits = 4)\n```\n\n::: {.cell-output-display}\n\n\n|Result                              |  Value|\n|:-----------------------------------|------:|\n|Observed likelihood-ratio statistic | 0.0529|\n|Classical p-value                   | 0.8181|\n\n\n:::\n:::\n\n\nThe likelihood-ratio statistic measures how much fit we gain by adding sex:\n\n$$\nT_{\\text{obs}}\n=\n2\\left\\{\n  \\ell(\\widehat{\\beta}_{\\text{full}})\n  -\n  \\ell(\\widehat{\\beta}_{\\text{reduced}})\n\\right\\}.\n$$\n\nA large value means that the full model improves substantially on the reduced\nmodel. The ordinary test compares this statistic with a chi-square reference\ndistribution.\n\n### Simulating crab data under the null hypothesis\n\nFor the WHZ test, we recentered the values so their mean was zero. Here the\nreduced model already represents the null hypothesis. It says that species\nprobability depends on width but not on sex.\n\nWe therefore take the probabilities fitted by the reduced model and use them\nto simulate a new species outcome for every crab. We then fit both models to\nthe simulated data and recalculate the likelihood-ratio statistic.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1503)\n\ncrab_null_probability <- fitted(crab_reduced)\ncrab_bootstrap_lrt <- numeric(n_boot)\n\nfor (b in seq_len(n_boot)) {\n  crab_star <- copy(crab_data)\n\n  crab_star[\n    ,\n    orange_species := rbinom(\n      n = .N,\n      size = 1,\n      prob = crab_null_probability\n    )\n  ]\n\n  reduced_star <- glm(\n    orange_species ~ CW,\n    family = binomial(link = \"logit\"),\n    data = crab_star\n  )\n\n  full_star <- glm(\n    orange_species ~ CW + sex,\n    family = binomial(link = \"logit\"),\n    data = crab_star\n  )\n\n  crab_bootstrap_lrt[b] <- as.numeric(\n    2 * (logLik(full_star) - logLik(reduced_star))\n  )\n}\n\nbootstrap_crab_p <- monte_carlo_p(\n  simulated_statistics = crab_bootstrap_lrt,\n  observed_statistic = observed_crab_lrt,\n  tail = \"right\"\n)\n\ncrab_test_comparison <- data.table(\n  Method = c(\n    \"Classical chi-square test\",\n    \"Parametric bootstrap test\"\n  ),\n  `p-value` = c(classical_crab_p, bootstrap_crab_p)\n)\n\nkable(crab_test_comparison, digits = 4)\n```\n\n::: {.cell-output-display}\n\n\n|Method                    | p-value|\n|:-------------------------|-------:|\n|Classical chi-square test |  0.8181|\n|Parametric bootstrap test |  0.8168|\n\n\n:::\n:::\n\n\nThe observed likelihood-ratio statistic is\n0.0529. The classical p-value is\n0.8181 and the bootstrap p-value is\n0.8168. The two p-values are almost the same and both\nare large. We therefore do not have evidence that adding sex improves the\nmodel after accounting for carapace width.\n\nThis follows the same procedure as the WHZ test. We state the null hypothesis,\ngenerate data under that hypothesis, recalculate the statistic, and find out\nhow often the simulated statistic is at least as large as the observed one.\n\nThis is a **parametric bootstrap** because the new species outcomes are\ngenerated from the reduced logistic model. The result therefore depends on\nthat model being a reasonable description of the data under the null\nhypothesis.\n\n## What bootstrap cannot rescue\n\nBootstrap is useful, but it is not magic.\n\n- It cannot correct a sample that systematically excluded important people.\n- It cannot turn 15 observations into the information contained in 15,000\n  independent observations.\n- It cannot ignore clustering, repeated measurements, survey weights, or time\n  order.\n- It cannot make a badly specified parametric model correct.\n- It cannot recover population patterns that are absent from the observed\n  sample.\n\n> Resampling a problem 5,000 times gives you 5,000 versions of the same\n> problem.\n\nFor independent observations, resampling rows may be reasonable. For a\nclustered survey, we may need to resample clusters. For longitudinal data, we\nmay need to resample people or blocks of time. For a regression, we must decide\nwhether to resample rows, residuals, clusters, or simulate from a fitted model.\n\nThe difficult part of bootstrap is often not writing the loop. It is deciding\nwhat represents a valid repeat of the study.\n\n## What should you ask when somebody says they bootstrapped the result?\n\nIf you are the PhD candidate, ask:\n\n- What statistic am I bootstrapping?\n- What exactly should be resampled?\n- Does that resampling respect how the data were collected?\n- For a hypothesis test, how did I make the null hypothesis true?\n- Did the bootstrap and conventional analysis tell the same practical story?\n- Would more bootstrap repetitions materially change the result?\n\nIf you are the manager listening to a presentation, ask:\n\n- What uncertainty does this interval describe?\n- Does the sample represent the people about whom we want to make a decision?\n- What assumptions were made when generating the bootstrap samples?\n- Would our decision change near the lower or upper end of the interval?\n\nThe next time a supervisor or statistician asks whether you bootstrapped the\nresult, you do not need to hear it as an incantation. They are asking how stable\nyour conclusion is when the observed data are made to play the role of many\npossible samples.\n\nYour next question should be:\n\n> What did we resample, and did we resample it in a way that respects how the\n> data were collected?\n",
    "supporting": [
      "boostrap_crab_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}